Feature fix login token and user info
jasondansie/exove-bch-project pull request #33
Opened 2023-05-16 14:03 UTC by jasondansie

I now use the email retrieved from ldap to search the mongoDB for the logged in user. I then load the token with the data from the mongoDB data. I believe this should fix the problems you were having. 

I believe I when to every link and made sure it worked. If you find a link that does not work let me know.

2023-05-16 14:12 UTC, CodeLaMat approved these changes, later dismissed
I changed the merging base from main to develop

2023-05-16 22:30 UTC, fsuh requested changes
the PR shows that there are some merge conflict between the branch and develop.  Please can you resolve the conflicts

2023-05-17 18:58 UTC, fsuh approved these changes

2023-05-18 07:49 UTC, CodeLaMat commented on frontend/src/components/hr/surveys/HRSurveys.tsx
> +  const role = userData[0].role;
This format does not work for me.

2023-05-18 07:51 UTC, CodeLaMat approved these changes
I approve despite the codes that I find bit suspicious.

2023-05-18 08:11 UTC, closed without merging

2023-05-18 08:12 UTC, jasondansie commented
canceling this for now, will try again later.